namespace DONT_TOUCH.Enums
{
    public enum CustomRoleType
    {
        None = 0,
        Cook = 1,
        Janitor,
        JuniorScientist,
        ContainmentSpecialist,
        Technician,
        BetterScp939,
        BetterScp106,
        BetterScp173,
        BetterScp049,
        BetterScp079,
        BetterScp096,
        Researcher,
        SeniorResearcher,
        ProjectManager,
        ScientificSecretary,
        SeniorEngineer,
        SeniorDoctor,
        DoctorSpecialist,
        Paramedic,
        PersonnelManager,
        Clerk,
        AdministrativeSecretary,
        SecurityPrivate,
        SecurityCorporal,
        SecuritySergeant,
        SecuritySupervisor,
        SecurityLieutenant,
        TsgPrivate,
        TsgCorporal,
        TsgSergeant,
        AlphaClass,
        BetaClass,
    }
}